#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the isBalanced function below.
def isBalanced(string):
    braces = { '(': ')', '{':'}','[':']'}
    stack = []
    for s in string:
        if stack and braces.get(stack[-1]) and braces[stack[-1]] == s:
            stack.pop()
            continue
        else: stack.append(s)
    if stack: return 'NO'
    return 'YES'


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    t = int(input())

    for t_itr in range(t):
        s = input()

        result = isBalanced(s)

        fptr.write(result + '\n')

    fptr.close()
