#!/bin/python3

import math
import os
import random
import re
import sys
from collections import Counter

# Complete the checkMagazine function below.
def checkMagazine(magazine, note):

    magazine_map = dict(Counter(magazine))
    note_map = dict(Counter(note))
           
    for key in note_map:
        if not magazine_map.get(key) or magazine_map[key] < note_map[key]:
            return 'No'
    return 'Yes'

if __name__ == '__main__':
    mn = input().split()

    m = int(mn[0])

    n = int(mn[1])

    magazine = input().rstrip().split()

    note = input().rstrip().split()

    print(checkMagazine(magazine, note))
